config/routes.rb
Rails.application.routes.draw do
  root 'contacts#index'
  resources :fields
  resources :contacts
  devise_for :users
  get 'about_challenge' => 'application#about_challenge'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :user
  has_many :field_values
  validates_presence_of :name, :email
end

app/models/field.rb
class Field < ActiveRecord::Base
  belongs_to :user
  has_many :field_values, dependent: :destroy
  validates_presence_of :name, :field_type
  enum types: {text_field: 'Text', text_area: 'Text Area', combobox: 'Combobox'}
end

app/models/field_query.rb
class FieldQuery
  def initialize(relation = Field.all)
    @relation = relation.extending(Scopes)
  end

  def search
    @relation
  end

  module Scopes
    def combobox_key_values
      where(field_type: Field.types[:combobox]).pluck('combobox_key_values')
    end
  end
end

app/models/field_value.rb
class FieldValue < ActiveRecord::Base
  belongs_to :field
  belongs_to :contact
  validates_presence_of :value
end

app/models/field_value_query.rb
class FieldValueQuery
  def initialize(relation = FieldValue.all)
    @relation = relation.extending(Scopes)
  end

  def search
    @relation
  end

  module Scopes
    def specific(contact_id, field_id)
      where(contact_id: contact_id, field_id: field_id)
    end

    def valued(contact_id, value)
      where(contact_id: contact_id, value: value)
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :fields
  devise :database_authenticatable, :registerable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception  

  def about_challenge
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  before_action :user_fields, only: [:edit, :new, :show]
  before_filter :authenticate_user!

  def index
    @contacts = Contact.where(user: current_user)
  end

  def new
    @contact = Contact.new
  end

  def show
  end

  def create
    @contact = Contact.new(contact_params)
    @contact.user = current_user

    custom_fields_params.each do |key, val|
      custom_field = Field.joins(:user).where(user_id: current_user.id, name: key).first
      field_value = FieldValue.new(value: val, contact: @contact, field_id: custom_field.id)
      field_value.save
    end

    if @contact.save
      redirect_to :contacts, notice: "Contact created successfully"
    else
      render action: :new, notice: "Could not save this contact"
    end
  end

  def edit

  end

  def update
    custom_fields_params.each do |key, val|
      custom_field = Field.joins(:user).where(user_id: current_user.id, name: key).first
      field_value = FieldValueQuery.new(custom_field.field_values).search.specific(@contact.id, custom_field.id)
      #field_value = FieldValueQuery.new(custom_field.field_values).search.from_contact(@contact.id))

      if field_value.exists?
        field_value.first.update(value: val)
      else
        field_value = FieldValue.new(value: val, contact: @contact, field_id: custom_field.id)
        field_value.save
      end
    end

    if @contact.update(contact_params)
      redirect_to contacts_path, notice: "Contact updated successfully"
    else
      redirect_to :contacts, notice: "Could not update this contact"
    end
  end

  def destroy
    if @contact.destroy
      redirect_to :contacts, notice: "Contact removed successfully"
    else
      redirect_to :contacts, notice: "Contact could not be removed"
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :email)
  end

  def custom_fields_params
    params.fetch(:custom_field, {}).permit!
  end

  def set_contact
    @contact = Contact.find(params[:id])
  end

  def user_fields
    @user_fields = current_user.fields
  end
end

app/controllers/fields_controller.rb
class FieldsController < ApplicationController
  before_action :set_field, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  def index
    @fields = current_user.fields
  end

  def new
    @field = Field.new
  end

  def show
  end

  def create
    @field = Field.new(field_params)
    @field.user = current_user

    if @field.save
      redirect_to :fields, notice: "Field created successfully"
    else
      render action: :new, notice: "Could not save this field"
    end
  end

  def edit

  end

  def update
    if @field.update(field_params)
      redirect_to :fields, notice: "Field updated successfully"
    else
      redirect_to :fields, notice: "Could not update this field"
    end
  end

  def destroy
    if @field.destroy
      redirect_to :fields, notice: "Field removed successfully"
    else
      redirect_to :fields, notice: "Field could not be removed"
    end
  end

  private

  def field_params
    params.require(:field).permit(:name, :field_type, :description, :combobox_key_values)
  end

  def set_field
    @field = Field.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |flash_key, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(flash_key)} alert-dismissible text-center", role: 'alert') do
        concat(content_tag(:button, class: 'close', data: { dismiss: 'alert' }) do
          concat content_tag(:span, '&times;'.html_safe, 'aria-hidden' => true)
          concat content_tag(:span, 'Close', class: 'sr-only')
        end)
        concat message
      end)
      flash.discard(flash_key)
    end    
    nil
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/fields_helper.rb
module FieldsHelper
  def generate_custom_field(field_name, field_type, field_value, options_string_values, disabled=nil)
    
    case field_type
    when 'text_field'
      text_field('custom_field', field_name, class: 'form-control', value: field_value)
    when 'text_area'
      text_area('custom_field', field_name, rows: 5, class: 'form-control', value: field_value)
    when 'combobox'
      options = options_string_to_hash(options_string_values)
      select('custom_field', field_name, options_from_collection_for_select(options, :first, :last, field_value), {},  disabled: disabled)
    end
  end

  def options_string_to_hash(options_string)
    options_string.split(',').map { |i| i.split(':').each { |e| puts e.strip! } }.to_h
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/about_challange.html.erb
<div class="row">
  <div
    class="col-xs-12 col-sm-6 col-md-4 col-lg-6 col-lg-offset-3"
  >
    <div class="well about_challange">
      <strong>Custom fields challenge</strong>
      <p> You must develop a contact list app with a login/logout system. It must allow users to create customized fields (text_field, text_area, combobox) that are not shared with other users.</p>
      <a class="btn btn-danger" href="https://github.com/romeromfm/rd-test" role="button" target="_blank">View source code on Github</a>

      <%= link_to 'Back', 'javascript:history.go(-1);', class: 'btn btn-default' %>
    </div>
  </div> 
</div>

app/views/application/about_challenge.html.erb
<div class="row">
  <div
    class="col-xs-12 col-sm-6 col-md-4 col-lg-6 col-lg-offset-3"
  >
    <div class="well about_challenge">
      <strong>Custom fields challenge</strong>
      <p> You must develop a contact list app with a login/logout system. It must allow users to create customized fields (text_field, text_area, combobox) that are not shared with other users.</p>
      <a class="btn btn-danger" href="https://github.com/romeromfm/rd-test" role="button" target="_blank">View source code on Github</a>

      <%= link_to 'Back', 'javascript:history.go(-1);', class: 'btn btn-default' %>
    </div>
  </div> 
</div>

app/views/contacts/_form.html.erb
<div class="row">
  <div class="col-lg-6 col-md-6 col-centered">
    <%= form_for(@contact) do |f| %>
      <% if @contact.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

          <ul>
          <% @contact.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :name %><br />
        <%= f.text_field :name, autofocus: true, class: 'form-control' %>
        <br />

        <%= f.label :email %><br />
        <%= f.email_field :email, class: 'form-control' %>
        <br />

        <% @user_fields.each do |user_field| %>
          <%= f.label user_field.name %> <br />
          <%= generate_custom_field(
            user_field.name,
            user_field.field_type,
            FieldValueQuery.new(user_field.field_values).search.specific(@contact.id, user_field.id).pluck('value').join(' '), 
            user_field.combobox_key_values)
          %>
          <br />
          <br />
        <% end %>
      </div>

      <div class="actions text-center">
        <%= f.submit 'Submit', class: 'btn btn-success'%>
        <%= link_to 'Back', contacts_path, class: 'btn btn-default' %>
      </div>
    <% end %>
  </div>
</div>

app/views/contacts/edit.html.erb
<h1 class="text-center">Editing Contact</h1>

<%= render 'form' %>

app/views/contacts/index.html.erb
<div class="row">
  <div class="text-center">
    <h1>Listing Contacts</h1>

    <br />

    <%= link_to 'New Contact', new_contact_path, class: 'btn btn-success' %>
  </div>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td>
          <%= link_to 'Show', contact, class: 'btn btn-primary' %>
          <%= link_to 'Edit', edit_contact_path(contact), class: 'btn btn-warning' %>
          <%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/contacts/new.html.erb
<h1 class="text-center">New Contact</h1>

<%= render 'form' %>

app/views/contacts/show.html.erb
<div class="row">
  <div class="col-lg-6 col-md-6 col-centered">
    <p id="notice"><%= notice %></p>

    <div class="panel panel-default">
      <div class="panel-heading text-center"><h3>Contact details</h3></div>
      <div class="panel-body">
        <h4>
          <strong> Name: </strong>
          <%= @contact.name%>
        </h4>
        <br/>

        <h4>
          <strong> E-mail: </strong>
          <%= @contact.email%>
        </h4>
        <br/>

        <% @user_fields.each do |user_field| %>
          <h4>
            <strong> <%= user_field.name %>: </strong>
            <% if user_field.field_type == 'combobox' %>
              <%= generate_custom_field(
                user_field.name,
                user_field.field_type,
                FieldValueQuery.new(user_field.field_values).search.specific(@contact.id, user_field.id).pluck('value').join(' '),
                user_field.combobox_key_values,
                'disabled')
              %>
            <% else %>
              <%= FieldValueQuery.new(user_field.field_values).search.specific(@contact.id, user_field.id).pluck('value').join(' ') %>
            <% end %>
          </h4>
          <br/>
        <% end %>
      </div>
    </div>

    <div class="actions text-center">
      <%= link_to 'Edit', edit_contact_path(@contact), class: 'btn btn-warning' %>
      <%= link_to 'Back', contacts_path, class: 'btn btn-default' %>
    </div>
  </div>
</div>

app/views/fields/_form.html.erb
<div class="row">
  <div class="col-lg-6 col-md-6 col-centered">
    <%= form_for(@field) do |f| %>
      <% if @field.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@field.errors.count, "error") %> prohibited this field from being saved:</h2>

          <ul>
          <% @field.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :name %><br />
        <%= f.text_field :name, autofocus: true, class: 'form-control' %>
        <br />

        <%= f.label :field_type %><br />
        <%= f.select :field_type, options_from_collection_for_select(Field.types.entries, :first, :last, @field.field_type), {}, onchange: "display_combobox_aux_field()" %>
        <br /><br />

        <div id="combobox_aux_field" style="display: none;">
          <label> Combobox key-values (ex.: val1: Value 1, val2: Value 2) </label> <br />
          <%= f.text_field :combobox_key_values, class: 'form-control' %>
          <br />
        </div>

        <%= f.label :description %><br />
        <%= f.text_field :description, class: 'form-control' %>
        <br />
      </div>

      <div class="actions text-center">
        <%= f.submit 'Submit', class: 'btn btn-success'%>
        <%= link_to 'Back', fields_path, class: 'btn btn-default' %>
      </div>
    <% end %>
  </div>
</div>

app/views/fields/edit.html.erb
<h1>Editing Field</h1>

<%= render 'form' %>

app/views/fields/index.html.erb
<div class="row">
  <div class="text-center">
    <h1>Listing Fields</h1>

    <br />

    <%= link_to 'New Field', new_field_path, class: 'btn btn-success' %>
  </div>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Description</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @fields.each do |field| %>
      <tr>
        <td><%= field.name %></td>
        <td><%= Field.types[field.field_type] %></td>
        <td><%= field.description %></td>
        <td>
          <%= link_to 'Show', field, class: 'btn btn-primary' %>
          <%= link_to 'Edit', edit_field_path(field), class: 'btn btn-warning' %>
          <%= link_to 'Destroy', field, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/fields/new.html.erb
<h1 class="text-center">New Field</h1>

<%= render 'form' %>

app/views/fields/show.html.erb
<div class="row">
  <div class="col-lg-6 col-md-6 col-centered">
    <p id="notice"><%= notice %></p>

    <div class="panel panel-default">
      <div class="panel-heading text-center"><h3>Field details</h3></div>
      <div class="panel-body">
        <h4>
          <strong> Name: </strong>
          <%= @field.name %>
        </h4>
        <br/>

        <h4>
          <strong> Field type: </strong>
          <%= Field.types[@field.field_type] %>
        </h4>
        <br />

        <h4>
          <strong> Description: </strong>
          <%= @field.description %>
        </h4>
        <br />

        <% if Field.types[@field.field_type] == Field.types[:combobox] %>
          <h4>
            <strong> Options: </strong>
            <%= select_tag @field.name, options_from_collection_for_select(options_string_to_hash(@field.combobox_key_values), :first, :last) %>
          </h4>
        <% end %>
        <br/>
      </div>
    </div>

    <div class="actions text-center">
      <%= link_to 'Edit', edit_field_path(@field), class: 'btn btn-warning' %>
      <%= link_to 'Back', fields_path, class: 'btn btn-default' %>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer text-center">
  <p>&copy; Romero Meireles - 2016</p>
</footer>

app/views/layouts/_head.html.erb
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="<%= t('generic.app_name') %>" />
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <title><%= t('generic.app_name') %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

</head>

app/views/layouts/_header.html.erb
<div class="header clearfix">
  <nav class="header-menu">
    <ul class="nav nav-pills pull-left">
      <% if current_user %>
        <li role="presentation"><%= link_to "My Contacts", contacts_path %></li>
        <li role="presentation"><%= link_to "My Fields", fields_path %></li>
      <% end %>

        <li role="presentation"><a href="<%= about_challenge_path %>">About this challenge</a></li>
      
      <% if current_user %>
        <li role="presentation"><%= link_to "Logout", destroy_user_session_path, method: 'delete' %></li>
        <li> <span class="label label-success user-hail"> <%= "Hi, #{current_user.email}" %> </span> </li>
      <% end %>
    </ul>
  </nav>

  <h2 class="pull-right"> <span class="label label-primary"> Resultados Digitais <span> </h2>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if IE 7]>
<html class="ie ie7" lang="en-US">
<![endif]-->
<!--[if IE 8]>
<html class="ie ie8" lang="en-US">
<![endif]-->
<!--[if !(IE 7) | !(IE 8)  ]><!-->
<html lang="en-US">
<!--<![endif]-->

  <%= render 'layouts/head' %>

  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <%= flash_messages %>
      <%= yield %>

      <%= render 'layouts/footer' %>
    </div>

    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>